// Per-shape codex content (EN). `blurb` is intuition-first; `term` is the edutainment "…this is called X"
// reward; `bond` is a character line (unlocks with bond level). Voiced/JA/ZH come via i18n later (M10).
// Sourced from CHARACTERS.md. Keyed by the family id used in the Rust content table.

export interface Codex {
  term: string
  blurb: string
  bond: string
}

export const CODEX: Record<string, Codex> = {
  sphere: { term: 'a sphere — the identity element of connected sum', blurb: 'Round from every side; the most efficient shape there is.', bond: 'I am a good thing to sit next to. That is a kind of Something.' },
  cube: { term: 'a cube — a Platonic solid, dual to the octahedron', blurb: 'Six flat faces. Put your cup down without spilling.', bond: 'Flat. Flat anywhere you look. That is it.' },
  tetrahedron: { term: 'a tetrahedron — the simplest solid, and its own dual', blurb: 'Four faces; it points right back at itself.', bond: 'I require no twin — I am my own reflection. …you will still sit with me, right?' },
  octahedron: { term: 'an octahedron — dual to the cube', blurb: 'Six sharp points; a cube with the corners filed off.', bond: 'Six points! Count them — touché.' },
  dodecahedron: { term: 'a dodecahedron — twelve pentagons, icosahedral symmetry', blurb: 'The same from twelve directions.', bond: 'One need not choose a face to show when every face is already given.' },
  icosahedron: { term: 'an icosahedron — twenty triangles, dual to the dodecahedron', blurb: 'The busiest of the Platonic solids.', bond: 'Twenty! …wait. Where was I.' },
  cylinder: { term: 'a cylinder — a developable (secretly flat) surface', blurb: 'A flat rectangle that committed.', bond: '…Are we done? Good.' },
  cone: { term: 'a cone — a ruled surface with one apex', blurb: 'One single, dramatic point.', bond: 'Is the tip too much? It is not too much. …right?' },
  disk: { term: 'a disk — the simplest bounded surface', blurb: 'A flat round wafer. A coaster.', bond: 'Resting. Just… resting.' },
  ellipsoid: { term: 'an ellipsoid — a sphere, stretched', blurb: 'Pip after a long stretch and a sigh.', bond: 'I have got the lanes, dear. You go and sit down.' },

  torus: { term: 'a torus — genus 1 (one hole), and secretly flat', blurb: 'There is always a way through me.', bond: 'Mind the hole. …Tea?' },
  mobius: { term: 'a Möbius strip — non-orientable; it has only one side', blurb: 'Walk all the way around and you come back mirror-flipped.', bond: 'One side. I keep telling people. Nobody believes a girl until she shows them.' },
  genus2: { term: 'a genus-2 surface — two holes, two lanes', blurb: 'Twice the holes, twice the fuss.', bond: 'Both lanes aligned. Twice-checked. Did senpai look?' },
  hyperboloid: { term: 'a hyperboloid — a doubly-ruled surface (made of straight lines)', blurb: 'Looks like a curve; built entirely of straight lines.', bond: '…it is nothing. Just straight lines, really.' },
  catenoid: { term: 'a catenoid — a minimal surface (the least film that spans its frame)', blurb: 'Pulled taut and even at every single point.', bond: 'I made it look effortless. It was not.' },
  helicoid: { term: 'a helicoid — the catenoid’s spiral twin', blurb: 'A spiral stair, forever climbing.', bond: 'Up — and up — race you, I love head starts.' },
  trefoil: { term: 'a trefoil — the simplest knot (three crossings)', blurb: 'Tangled, and it cannot be undone.', bond: 'I can’t be undone. That is just— my whole edge is Surface.' },
  monkey_saddle: { term: 'a monkey saddle — three-way fairness', blurb: 'A dip for each leg — and one, crucially, for the tail.', bond: 'Three ways down. It is only fair.' },

  klein_bottle: { term: 'a Klein bottle — non-orientable, with no inside', blurb: 'Go on, try to pour me a drink.', bond: 'Someone get a towel for the void. The void is, I confess, mostly steam.' },
  roman_surface: { term: 'the Roman (Steiner) surface — ℝP² drawn as Steiner’s four-lobed quartic, three pinch-creases and no inside', blurb: 'Four kisses, three creases, and not one inside.', bond: 'Four lobes that meet at the middle, three seams where I cross — and still just the one side. Boy says it with a bow; I say it with a quartic.' },
  boys_surface: { term: "a Boy's surface — the projective plane immersed gracefully in 3D", blurb: 'The same soul as ℝP², done with poise.', bond: 'You say it with a wince; I say it with a bow.' },
  whitney_umbrella: { term: 'a Whitney umbrella — the pinch-point where a surface crosses itself, two sheets meeting along a seam that runs off to a single point', blurb: 'Two sheets, one pinch, and a seam that never closes.', bond: 'Two sheets fold down to one sharp point — and the seam between them never quite shuts. Mind the pinch.' },
  figure8_knot: { term: 'a figure-eight knot — amphichiral (its own mirror image)', blurb: 'Looks in the glass and finds nothing to fix.', bond: 'Hm. Still me.' },
  torus_knot_2_5: { term: 'a (2,5) torus knot — it lives on the surface of the torus', blurb: 'Wound into the donut; that’s my home address.', bond: 'Try lifting me off her. I literally stop being a knot.' },
  gyroid: { term: 'a gyroid — a triply-periodic minimal surface', blurb: 'A weave inside a weave, repeating forever.', bond: 'I tend the garden — a smaller garden, inside which a smaller garden…' },
  schwarz_p: { term: 'a Schwarz-P surface — the cubic minimal lattice', blurb: 'Everything kept at clean right angles.', bond: 'One true thing. And then I stop.' },

  heptoroid: { term: 'a heptoroid — genus 7 (seven holes, seven lanes)', blurb: 'Seven lanes, all green. Go rest — onee-san’s got it.', bond: 'Lane four and six at once— oh no— I’m fine. I’m FINE.' },
  costa: { term: 'a Costa surface — a complete minimal surface with three ends', blurb: 'Balanced everywhere. Not mostly. Everywhere.', bond: 'You counted the third end. Everyone stops at two. That is the whole thing.' },
  borromean: { term: 'Borromean rings — three loops, no two of them linked', blurb: 'Remove any one and all three fall. Load-bearing, not clingy.', bond: 'We are all three simultaneously not crying. That is how we do everything.' },
  seifert: { term: 'a Seifert surface — the membrane whose only edge is a knot', blurb: 'On my own, a quiet sheet. Hand me a knot, and I complete it.', bond: 'Neither of us is whole alone, and we are both completely fine with that.' },
  lorenz: { term: 'a Lorenz manifold — a strange attractor (the gacha’s own engine)', blurb: 'Completely determined… and utterly unpredictable. There’s a difference!', bond: 'Same pebble, same moment, same loop-de-loop. Ooh — butterfly.' },
  schwarz_d: { term: 'a Schwarz-D surface — two interwoven infinite labyrinths', blurb: 'Two worlds, one wall. I keep the wall.', bond: 'You kept walking until the pattern became home. Stay. There is infinitely much room.' },
  triple_torus: { term: 'a triple torus — genus 3 (three holes)', blurb: 'Three lanes. Only three. But mine are TIDY holes.', bond: 'Remember when order didn’t matter? …don’t tell senpai I said it was easier.' },

  tesseract: { term: 'a tesseract — the 4-cube; you only ever see its 3D shadow', blurb: 'A box inside a box, from where you stand.', bond: 'You see all eight rooms at once now. …It’s nice, being seen whole. Don’t tell Hex.' },
  cell_16: { term: 'a 16-cell — the tesseract’s dual; the 4D cross-polytope (an octahedron, ascended)', blurb: 'A pure tone, a perfect blue, and absolutely no negotiation.', bond: 'Hold still — I only hum before I decide. The pattern reads blue. …it’s not like I was aiming at you. Don’t make it weird.' },
  cell_24: { term: 'a 24-cell — self-dual, with no analogue in any other dimension', blurb: 'There is no one quite like me. I checked every dimension.', bond: 'My mirror is me — but the Atlas is a mirror too, and now there are more of me. Thank you.' },
  cell_120: { term: 'a 120-cell — 600 vertices; the crown of the fourth dimension', blurb: 'They call me the crown jewel. I prefer “the one who leaves the porch light on.”', bond: 'You look flat from up here. And lovely. Come up.' },
  cell_600: { term: 'a 600-cell — the 120-cell’s dual; a storm of tetrahedra', blurb: 'A cathedral? Pretty. I am the WEATHER.', bond: 'When I rattle the windows, it’s only ever my sister’s house. I’d never crack a pane.' },
  klein_quartic: { term: 'a Klein quartic — genus 3 with the maximum possible symmetry (168)', blurb: 'Hum a note; I’ll find the other hundred-sixty-seven that agree.', bond: 'The full chord, all hundred-sixty-eight at once. It sounds like a choir because it is one.' },
  hopf: { term: 'the Hopf fibration — fill a 4-ball with circles, every pair interlinked', blurb: 'Two of you are already linked. You simply haven’t met.', bond: 'The whole Atlas was one linked structure the entire time. So were you.' },
  mazur: { term: 'a Mazur manifold — sounds like a monster; is secretly contractible (a ball)', blurb: 'BEHOLD, the manifold that should not be— …it’s fine. Please don’t run.', bond: 'I look impossible, but I shrink to a single harmless point. “Looks scary, is soft” is allowed.' },

  // Relics — the patron saints of computer graphics (washed up from the rendering-folk's workshops)
  utah_teapot: { term: 'the Utah Teapot — Martin Newell, 1975; the most-rendered object in history', blurb: 'I have no bottom. Everyone drew me anyway.', bond: 'Spout, handle, lid, body — and, famously, no base. You rendered me regardless. You always do.' },
  stanford_bunny: { term: 'the Stanford Bunny — scanned in 1994; a benchmark ever since', blurb: 'Scanned once. Hopping through every paper since.', bond: 'They scanned me from a little clay figurine and I never left the literature. Hello again.' },
  benchy: { term: '3DBenchy — the calibration boat every 3D printer is tested on', blurb: 'Born to be torture-tested.', bond: 'Overhangs, a chimney, a tiny window — all to make printers sweat. I was built to be hard. I don’t mind.' },
  stanford_dragon: { term: 'the Stanford Dragon — the model you render to show off light', blurb: 'Bring your best subsurface scattering.', bond: 'Every renderer cuts its teeth on my scales. Go on — show me what your light can do.' },
  suzanne: { term: 'Suzanne — Blender’s monkey-head test model', blurb: 'The monkey who tests everything.', bond: 'Press the button and I appear — the quick way to check a shader. Tested more than anyone alive.' },
  spot: { term: 'Spot — Keenan Crane’s cow, mascot of geometry processing', blurb: 'I taught a generation conformal maps.', bond: 'A friendly cow, parameterised more lovingly than most. Moo — in the language of discrete differential geometry.' },
  endrass_octic: { term: 'an Endrass octic — a degree-8 surface that carries 168 ordinary double points, the most any octic is known to allow', blurb: 'A hundred and sixty-eight sparks, every one a place where I cross myself.', bond: 'Mascot? No. I am a record-holder. Count my crossings if you doubt me — go on, I’ll wait.' },
  armadillo: { term: 'the Stanford Armadillo — a high-detail scan benchmark', blurb: 'Plates, claws, and a million triangles of attitude.', bond: 'Scanned in fine detail to stress every algorithm going. I am dense. I contain multitudes — mostly polygons.' },
  lucy: { term: 'Lucy — the Stanford angel, scanned from a marble statue', blurb: 'Eight metres of marble, one tidy mesh.', bond: 'An angel holding a torch, digitised to the millimetre. I have been a benchmark longer than some of you have been rendered.' },
  csaszar: { term: 'the Császár torus — a 7-vertex polyhedron where every pair of corners shares an edge', blurb: 'A donut with only seven corners, and no diagonals at all.', bond: 'Seven vertices, twenty-one edges, every pair joined — a torus stripped to the bone. Minimalism, with a hole in it.' },
  menger: { term: 'the Menger sponge — a cube with square tunnels drilled through it, forever', blurb: 'Drill a hole through every face, then do the same to what is left, endlessly. Mostly holes; barely there.', bond: 'Infinite surface, zero volume. I am the most of nothing you will ever hold.' },
  sierpinski: { term: 'the Sierpiński tetrahedron — a pyramid built from ever-smaller copies of itself', blurb: 'A pyramid of pyramids of pyramids, hollow all the way down.', bond: 'Look closer and it is me again. And again. We are all the same shape, only smaller.' },
  clifford_torus: { term: 'the Clifford torus — a perfectly flat torus that only fits, unstretched, inside the 3-sphere in four dimensions', blurb: 'An ordinary donut must curve to live in our space. This one is flat everywhere — no stretching anywhere — but that perfection only exists in 4D.', bond: 'I am a flat donut from the fourth dimension. Down here you only ever meet my shadow.' },
  cable_knot: { term: 'a cable knot — a satellite knot whose strand is itself tied into a knot', blurb: 'Tie a knot. Now take the very rope it is made of and tie that into a knot too. A knot wearing a knot.', bond: 'Knots within knots. Unravel me and you will only find more of me.' },
  mandelbulb: { term: 'the Mandelbulb — the 3D answer to the Mandelbrot set, raised to the 8th power', blurb: 'Take a point, square it eight times in spherical coordinates, add it back, repeat. The points that never fly off make this bulbous, coral-like fractal — lobes growing lobes growing lobes.', bond: 'I am the Mandelbrot set, freed into three dimensions. Spin me and you fall in forever.' },
  mandelbox: { term: 'the Mandelbox — a fractal built from folding space (box-fold) and inverting it (sphere-fold)', blurb: 'Fold every point back inside a box, turn it inside-out through a sphere, scale, repeat. Out comes an endless metallic city of ledges and shafts.', bond: 'I am made of nothing but folds. Step in and the corridors rebuild themselves around you.' },
  julia: { term: 'a quaternion Julia set — the Mandelbrot iteration run in 4-dimensional numbers, then sliced to 3D', blurb: 'Numbers with four parts instead of two. Square and add a fixed seed; the points that stay home form this shape. Pick a different seed and you get a wholly different creature.', bond: 'I live in four dimensions. What you hold is just my shadow, and even that is endless.' },
  apollonian: { term: 'the Apollonian gasket — circles (here spheres) packed into the gaps between circles, forever', blurb: 'Three mutually-touching circles always leave two gaps, each begging for a smaller circle, which leaves more gaps. Carried into 3D it becomes a froth of nested spheres.', bond: 'Every gap between us is an invitation. There is always room for one more.' },
  kleinian: { term: 'a Kleinian limit set — the fractal dust left behind by a group of reflecting spheres', blurb: 'Take a handful of mirrors arranged in space and bounce a point around forever; the places it can reach form this lacework of arches and spires.', bond: 'I am where the mirrors agree to meet. Endlessly reflected, never quite repeating.' },

  // ── NG+ cohort expansion: 4D cross-sections (Meta) + a TPMS pair & a Julia fractal (Transcendent) ──
  spherinder_slice: { term: 'a spherinder slice — the 3D shadow of a spherinder (a ball swept along a fourth-dimension interval)', blurb: 'In four dimensions I am a ball dragged sideways into a little tube. Cut me back down to your space and you get this: a softly rounded slab.', bond: 'I am thicker than I look — most of me is one dimension over. This is just the slice you can hold.' },
  duocylinder: { term: 'a duocylinder — a perfectly flat torus in 4D, whose ridge has a square cross-section', blurb: 'Spin a square around two different circles at once and you need four dimensions to do it. The seam left behind is a flat, square-edged donut: Cliff’s cornered cousin.', bond: 'Two circles, turning at right angles I can’t show you down here. The corners are the only part that fits.' },
  cell24_section: { term: 'a cuboctahedron — the equatorial slice through the 24-cell, the one 4D shape with no lower-dimensional echo', blurb: 'Slice the self-dual 24-cell straight across its middle and out falls a cuboctahedron: a cube and an octahedron sharing the same corners, half of each.', bond: 'Square faces, triangle faces, all from one clean cut. I’m the 24-cell’s waistline — and I rather like the view.' },
  ditorus: { term: 'a ditorus — a torus of a torus, the 3D shadow of a 4D toratope', blurb: 'Take a donut. Now bore a second tunnel all the way through the dough itself — a hole running through my hole. A ring threaded through a ring, both at once.', bond: 'There’s a loop inside my loop, dear — and inside that, well, who’s counting. Mind both holes. …Tea? It goes round twice.' },
  hyperbolic_honeycomb: { term: 'the {4,3,5} hyperbolic honeycomb — cubes packed five-around-an-edge in curved (hyperbolic) space, an infinite tessellation that only fits where space itself bends', blurb: 'Every arch you walk under is the same arch. Keep walking; there are infinitely many, and they’re all home.', bond: 'Five cubes meet at every edge — try it in flat space and they won’t fit, so space leans aside to make room. An endless cloister, and every cell is mine.' },
  aizawa_attractor: { term: 'the Aizawa attractor — a strange attractor: a path that is utterly determined yet never once repeats, winding forever around a pinched funnel', blurb: 'Same nudge, same start, every time… and I never once trace the same path. Determined isn’t the same as predictable!', bond: 'Give me the very same push from the very same spot and watch — I still wander somewhere new. Lorrie and I are the chaos cousins. We just spin different funnels.' },
  barth_sextic: { term: 'the Barth sextic — a degree-6 surface carrying 65 ordinary double points, the most any sextic can have, with the full symmetry of the icosahedron', blurb: 'I have sixty-five secret dimples, and I wear them like a crown.', bond: 'Sixty-five pinch-points, not one more allowed — and arranged with an icosahedron’s symmetry. A record, worn lightly. Count them if you like; I shan’t mind.' },
  twisted_torus: { term: 'a twisted torus — a ring whose tube rotates as you travel around it', blurb: 'Take a donut and spin its cross-section as it loops. The surface winds into a ribbon; two full turns and it closes back on itself.', bond: 'Still a torus at heart. I just never sit still.' },
  cut_hollow_sphere: { term: 'a spherical cap — a hollow sphere sliced by a plane, kept as a thin open shell', blurb: 'Slice a hollow ball and keep one piece: a bowl. A single rim, two sides, nothing sealed in.', bond: 'I used to be a whole sphere. Now I am a place to put things.' },
  blobby: { term: 'a metaball blob — round forms melted together with smooth (soft-minimum) blends', blurb: 'Start with a ball, grow an arm toward each direction, and let every seam melt instead of crease. No edges, no holes — just smooth, bulging unity.', bond: 'Three pairs of arms, all melted into one body. Hold whichever you like.' },
  dini: { term: "Dini's surface — a pseudosphere coiled into a spiralling horn of constant negative curvature", blurb: 'A seashell that curves the same way — the wrong way — at every single point.', bond: 'Every point of me bends like a saddle. I have been twisting since before you looked.' },
  torus_knot_2_7: { term: 'a (2,7) torus knot — one loop that winds seven times around before it closes', blurb: 'A single unbroken thread, looped into a seven-pointed star.', bond: 'Seven crossings, one strand. Try to untangle me — you cannot, and I rather like that about us.' },
}
